name: CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull Changes
        run: git pull origin dev
        working-directory: /home/prathammishra/interact/interact-admin-microservice

      - name: Build and Deploy
        run: |
          sudo docker compose up --build -d
        working-directory: /home/prathammishra/interact/interact-admin-microservice
